project:
  type: website
  output-dir: docs
  resources:
    - "files/"

website:
  title: "EBIO 5460: Causal Inference in Ecology"
  site-url: "https://katherinesiegel.github.io/EBIOcausalinference/"

  navbar:
    pinned: true
    background: "#20618D"
    tools:
      - icon: github
        href: https://github.com/katherinesiegel/EBIOcausalinference
        text: GitHub
    right:
      - href: index.qmd
        text: Course Overview
      - href: schedule.qmd
        text: Schedule
      - href: readings.qmd
        text: Readings & Additional Materials
      - href: assignments.qmd
        text: Assignments & Evaluation
      - href: exercises/index.qmd
        text: Exercises
      - href: coding_resources.qmd
        text: Coding Resources
      - href: policies.qmd
        text: University Policies

  sidebar:
    # background: "#20618D"
    # pinned: true
    # align: center
    # style: docked
    - title: "Exercises"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Overview"
          contents:
            - exercises/index.qmd
        - section: "Matching"
          contents:
            - exercises/matching_demo.qmd

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

