project:
  type: website
  output-dir: docs

website:
  title: "EBIO 5460: Causal Inference in Ecology"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/katherinesiegel/EBIOcausalinference
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Course Overview
      - href: schedule.qmd
        text: Schedule
      - href: readings.qmd
        text: Readings & Additional Materials
      - href: assignments.qmd
        text: Assignments & Evaluation
      - href: coding_resources.qmd
        text: Coding Resources
      - href: policies.qmd
        text: University Policies

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

