---
title: "Assignments & Evaluation"
---

The main assignment will be either to complete and write up a data analysis or to do a literature review and deep dive on a particular subtopic (ideas listed below). The project or literature review will culminate in a presentation the last week of classes and a final written report.  

As a 3-credit graduate course, our expectation is that you are here to learn, which involves following along with the course through doing the reading and attending class meetings. We are less interested in grades and more interested in providing a venue to hold you accountable for learning the material. We will provide many opportunities for feedback and workshopping, so completing your assignments and making progress on your project will benefit your learning (and hopefully contribute to your progress on your thesis/dissertation). As such, attendance and participation is 25%, leading of paper discussion/presentation is 25%, and the final report and presentation are worth the remaining 50%. 

**Final Project Option 1: Data analysis project**  
For the final project that takes the form of a data analysis, each student will complete a project according to the following process: identifying a research question, creating a DAG, choosing and applying a data analysis, and writing up a methods and results section that 1) articulates the causal relationship of interest, 2) describes the causal identification strategy and choice of study design/methods, 3) describes the implicit assumptions on which this strategy rests, and 4) interprets the results and their potential biases. *We encourage students to base this analysis on their thesis research to get the most out of the class.*  

**Final Project Option 2: Literature review**  
Alternatively, students can complete a literature review that provides a deeper dive on a topic we do not cover in detail in this course (*some ideas are listed below). This direction may be more appropriate for students who are not at a stage of performing analyses for their thesis, who do not have a relevant project that is tackling an empirical causal question, or who are interested in learning more about a topic not covered under our guidance. 

**Additional assignments**  
In addition to the project/literature review, each student will also lead a paper(s) discussion during the semester, which will be either a discussion of a paper describing or applying a study design or a critique of a paper aiming to address a causal question. When leading the paper discussions, we recommend starting off with drawing a diagram of the causal relationships in question in the paper.  

**Readings**  
The course reading list will include journal articles and book chapters that we will make available to you on our course website. Throughout the semester, the class will compile a running glossary of “jargon” and terms and concepts in causal inference to provide notes as reference. We (the instructors) will provide a bibliography of additional readings and coding resources on various topics for students as reference.  

The readings differ in their depth and use of math and notation. *You do not need to understand all the equations and notation to gain intuition about the material and concepts.* Try to learn it but try not to be too stressed by it. 

Suggestions for literature review topics (you are not limited to these topics, but here are some ideas):  
1) Challenges and solutions for experimental designs and interpretation (choose one):
    a) Non-compliance and attrition (this is a rich area!)
    b) Interference between experimental units and spillovers (G&G Ch8)
    c) Partial identification (excludability violations)
    d) Mechanisms and mediation analysis (G&G Ch 10)
    e) Limits to what experiments tell us about heterogenous treatment effects 
    f) Integration of experimental findings (e.g., meta-analyses and extrapolation)
2) New issues for difference-in-difference and two-way fixed effects estimators (e.g., staggered treatments and heterogeneity
3) Synthetic control methods (https://mixtape.scunning.com/10-synthetic_control)
4) Machine learning and causal inference
5) Sensitivity analyses and/or placebo designs
6) Weighted regression (extension of matching ideas)
7) Mechanism (Mediation) Analysis; Sequential G estimation
8) Remote sensing and causal inference
9) Systematic measurement error
10) Causal identification in time series
11) Inferences in observational designs and networks
12) Meta-analyses using observational data
