---
title: "Coding Resources"
---

Programming in R will be a key part of this course, and as most of you have probably experienced, R can cause headaches and stress! Files go missing, package dependencies spiral out of control, and minor code errors can cost us hours of troubleshooting. The point of this course is not to become an R whiz, and we don’t want code errors to get in the way of your learning and research progress. 

We encourage you to use online resources for coding help if/when you get stuck. [StackOverflow](https://stackoverflow.com/) is a great resource for finding solutions to coding issues or asking a specific question, as is the [RStudio Community](https://community.rstudio.com/, currently in transition as RStudio becomes Posit). Twitter can also be a great resource: if you post a question with the hashtag #rstats, a kind soul might give you an answer. If you’re looking for help via Google, we recommend including in your query the package you’re using and if applicable, the error message you’re getting. Finally, if you are a visual learner, [Allison Horst](https://allisonhorst.com/) has some great learning tools for various R functions. 


**If you could use some more training and exposure to R, here are some resources to get started:**  

* [swirl](https://swirlstats.com/) teaches you R programming and data science interactively, at your own pace, and right in the R console! On this page, swirl will walk you through each of the steps required to begin using R and swirl today!  
* [R for data science (R4DS)](https://r4ds.had.co.nz/). R4DS teaches you how to do data science with R: You’ll learn how to get your data into R, get it into the most useful structure, transform it, visualize it and model it. The book is available online, where you can find a practicum of skills for data science from visualization to wrangling and writing functions.  
* Have a favorite resource? Please send it to Laura and Katherine so we can post it! 
