---
title: "EBIO 5460: Causal Inference in Ecology"
---

## Instructors
[Laura Dee](https://www.colorado.edu/ebio/laura-dee) (laura.dee@colorado.edu)   
[Katherine Siegel](https://katherinesiegel.github.io/) (ksiegel@ucar.edu)   

## Class Meetings
Mondays & Wednesdays 3:30-4:45pm  

### Office Hours  
Laura: Wednesday 2:15-3:15 pm and by appointment  
Katherine: Tuesday 3-4pm and by appointment  

## Course Description  
How does biodiversity effect ecosystem functioning? What are the consequences of temperature variability for parasite loads and host populations? How do plant communities respond to drought, and which ecosystems respond most? Do restoration and conservation work? How does climate change affect disturbance regimes? Cause and effect questions like these motivate much of the empirical work in basic and applied ecological and environmental sciences. Does X cause Y? If X causes Y, does it cause Y in all situations? Through what mechanisms does X cause Y? If X causes Y, how large is the effect of X on Y and how does the size compare to other causes of Y? To answer these cause-and-effect questions, a counterfactual model of causality and a unified methodological framework has been developed yet is not often taught or emphasized in ecology and EBIO more generally. Now this framework is the predominant approach for causal inference in a diversity of fields including public health, economics, and computer science  (which is also referred to as program evaluation or impact evaluation).  

Given the increasing access to spatiotemporally large observational datasets (e.g., remotely sensed data, data from long-term ecological monitoring), we have unprecedented opportunities to answer questions about causal relationships and mechanisms outside of the context of traditional ecological approaches to experimental design. Deriving causal inferences from observational data presents its own set of challenges, and this course presents statistical methods to overcome challenges for causal inference in both observational and experimental study designs.  

This class aims to teach students to apply and interpret the counterfactual causality model and associated methods in answering empirical questions in basic and applied ecology. As a 3-credit graduate course, this course has a corresponding reading load with an emphasis on readings that elucidate the intuition and the application of the core conceptual ideas. We are firm believers that the most fundamental principles can be stated in plain English and conceptual understanding is just as important as the math. Thus the course stresses intuition (in English) over mechanics and proofs. Nevertheless, students will be expected to apply the mechanics in replication exercises in R statistical software and in a final a project related to the students’ thesis.  

Whether you are a student with substantial graduate work in empirical methods or a student with only the basic pre-requisites covered (some introductory statistics or biostatistics is required), you should expect to gain a deeper understanding of approaches to answering causal questions and of the nature of evidence. Importantly, you will see more clearly the conceptual connections among the various approaches to estimating causal effects – experiments and observational analyses. Even for students with substantial coursework in statistics, these connections are often missed.   

While most students who will take this class are in EBIO fields, you should expect to do readings outside of EBIO areas and to see examples from other fields – because ecology and evolutionary biology is lagging behind other fields in several areas we will cover. On the bright side, reading beyond the typical EBIO papers will provide you with an entry point into the broader literature on causal inference, stemming from economics, public health, epidemiology, political science, and other fields. Thus, we see the use of broader readings and examples as intentional to meet the course’s learning objectives, and as a potential competitive advantage – and a way to expand your thinking – rather than a distraction from topics that interest you most. In our experience, gaining perspective on methods and language used in other fields will also provide you with skills to foster collaborations across disciplines. We will also invite guest speakers who are experts to showcase applications of the theory and approaches to questions and data in ecology, conservation, and evolution/behavior – and present some of our in-progress research using causal inference approaches applied to EBIO.  

We have outlined a provisional syllabus below, but we can adapt it based on student interests and background. The main emphasis of the course is like any other graduate course: to encourage students to think critically, to speak and write simply and clearly, collaborate, to own and use a body of facts and ideas that are widely known, to detect errors and fallacies, to resolve intellectual problems, and to advance our collective knowledge through independent research and applied statistics.  

## Course Prerequisites 
Some introductory statistics or biostatistics that covers hypothesis testing and regression is required.  Some familiarity with R as a programming language is also recommended. This course will be most beneficial to students who have started their thesis work and can incorporate an empirical analysis into the class project, but it is open to all students who meet the pre-requisites. Contact the professors if you are unsure whether your background is sufficient for the course.

## Course Objectives  
Through this course, students will gain:

1. An understanding of the main frameworks for counterfactual causal inference and how causal inference differs from other empirical research aims
2. Familiarity with how causal inference is applied in experimental and quasi-experimental study designs in ecology and evolution
3. Experience reading the published literature in ecology and evolutionary biology with a critical eye towards appropriate use of methods for identifying causal relationships and mechanisms.  

This course aims for students to learn how to:

1. Summarize key threats to causal inference and identify these threats when evaluating their own and published study designs
2. Apply causal inference methods to real world research questions and datasets – either through applications to their thesis work or to other datasets – to mitigate threats to causal inference through research design
3. Identify the most appropriate study design(s) and methodology in non-experimental settings in light of the available data and the research question
4. Implement these designs and methods in R and appropriately interpret the results and their potential biases
5. Write and speak clearly about these methods and the results they yield.  

## Code & Data
We will make RMarkdown Files, datasets, and code available at https://github.com/LauraDee/CausalEcology  

## A Note on Inclusion  
Some of the texts that we will read in class use examples to illustrate their points that are problematic (e.g., treating gender as a binary or studying post-colonial economic development without considering the violence of colonialism). We do not agree with the assumptions underlying these examples and we acknowledge the problems with them. The descriptions of methods are still some of the easiest to read out there. At the same time, policy decisions are being made based on these and similar analyses, so we need to train people who can use these methods for causal inference **and** approach this work through a lens of diversity, equity, inclusion, and justice.  

In this class, we aim to foster discussions of how bias shapes causal models in science, the questions we ask, the analyses we do, who does them, and our interpretation of these results. We are also always open to feedback on these subjects.

