---
title: "Readings & Additional Materials"
---

## Recommended Textbooks (not required)    
We do not expect you to buy any/all of these books. We will provide the sections that are assigned for class. But if you want to explore topics of causal inference further, we recommend these books!  

*Note: Some of these texts use examples to illustrate their points that are problematic (e.g., treating gender as a binary or studying post-colonial economic development without considering the violence of colonialism). We do not agree with the assumptions underlying these examples and we acknowledge the problems with them. The descriptions of methods are still some of the easiest to read out there.*

* Morgan, SL and C Winship. 2007. [*Counterfactuals and Causal Inference: methods and principles for social research*](https://doi.org/10.1017/CBO9781107587991).  
* Gerber, AS and DP Green. 2012. [*Field Experiments: design, analysis and interpretation*](https://wwnorton.com/books/9780393979954). (especially useful if you plan to do field experiments in your research)  
* Cunningham, S. 2021. [*Causal Inference: The Mixtape*](https://mixtape.scunning.com/) (New Haven, CT: Yale University Press). [Available online for free](https://mixtape.scunning.com/)  
* Angrist, JD and JS Pischke. 2015. [*Mastering ’Metrics: The Path from Cause to Effect*](https://www.masteringmetrics.com/) (Princeton, NJ: Princeton University Press).  
* Angrist, JD and JS Pischke. 2008. [*Mostly Harmless Econometrics: an empiricist’s companion*](https://www.mostlyharmlesseconometrics.com/). (Princeton, NJ: Princeton University Press).  
* Rosenbaum, P.  2010. [*Observational Studies*](https://doi.org/10.1007/978-1-4757-3692-2). Springer.  
* Pearl, J. and D. Mackenzie. 2018. [*The Book of Why*](https://dl.acm.org/doi/10.5555/3238230). (New York, NY: Basic Books, Inc.) (A more popular science book)  
* For more technical discussions of causality:  
    + [Holland 1986, JASA](https://doi.org/10.2307/2289064)  
    + [Heckman 2000, QJE](https://www.jstor.org/stable/2586935)    
    + Pearl, J. 2009. [*Causality*](https://doi.org/10.1017/CBO9780511803161). (Cambridge, UK: Cambridge University Press).  
       

## Due Mon. 1/23  

1) [Hernan et al. 2019](https://doi.org/10.1080/09332480.2019.1579578)
2) Angrist & Pischke 2008, Chapter 1  
3) Gerber & Green, Chapter 1 (you can just skim this one)    

## Due Wed. 1/25  

1) Angrist & Pischke 2008, Chapter 2  
3) [Hernan 2016](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5207342/)  

\textcolor{orange}{Student discussion lead(s):}

## Due Mon. 1/30  
Guest speaker: Dr. Zach Laubach

1) [Rohrer 2018](https://journals.sagepub.com/doi/epub/10.1177/2515245917745629)
2) [Laubach et al. 2021](https://doi.org/10.1098/rspb.2020.2815)  

## Due Wed. 2/1  
Come to class prepared to present and discuss your DAG.

1) [Arif & MacNeil 2022](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecm.1554)  
2) Watch Hernan video: "3. Elements of DAGs" on Canvas
3) Check out [DAG software](http://dagitty.net)  

#### Optional  
For additional background on DAGs:  

4) Morgan & Winship (2007) pgs. 29-34 and Ch. 3 - see Canvas
5) [Cunningham (2021) Ch. 3](https://mixtape.scunning.com/03-directed_acyclical_graphs)  

Other software for making DAGs:  
a) [ggdag](https://cran.r-project.org/web/packages/ggdag/vignettes/intro-to-ggdag.html) is a nice R package based on dagitty but tidyverse-compatible and with much better plotting functionality    
b) [shinydag](https://www.gerkelab.com/project/shinydag/) is another GUI aimed at visualizing DAGs and exporting them in different publication-ready formats  
c) [TETRAD](https://sites.google.com/view/tetradcausal)  
d) [DAG program](https://hsz.dife.de/dag/)  
e) [dagR](https://journals.lww.com/epidem/Fulltext/2010/07000/dagR__A_Suite_of_R_Functions_for_Directed_Acyclic.26.aspx)

## Due Mon. 2/6  

1) Gerber & Green, Chapter 2
2) [Kimmel et al. 2021](https://pubmed.ncbi.nlm.nih.gov/34538502/)  

## Due Wed. 2/8 [Casey]   

1) No readings today!

## Due Mon. 2/13  

1) Watch Imbens video: [2022 Nobel Prize lecture](https://www.nobelprize.org/prizes/economic-sciences/2021/imbens/lecture/)
2) [Ferraro 2009](https://doi.org/10.1002/ev.297)  

## Due Wed. 2/15 [Brendan & Henry]    

1) [Butsic et al. 2017](https://www.sciencedirect.com/science/article/pii/S1439179116301323)  
2) [Larsen et al. 2019](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13190)  

## Due Mon. 2/20  

1) [Ramsey et al. 2018](https://doi.org/10.1111/2041-210X.13111)
2) [Stuart 2010](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2943670/)  

## Due Wed. 2/22 [Alec & Sam]    

1) [Siegel et al. 2022](https://doi.org/10.1007/s10113-022-01950-y)  
2) [Xu et al. 2022](https://www.science.org/doi/10.1126/sciadv.abo0119)  
3) Siegel et al., submitted (available on Canvas)

## Due Mon. 2/27  

1) Angrist & Pischke **2015**, Chapter 5 (note: this is in *Mastering ‘Metrics*)  

## Due Wed. 3/1 [Anna & Hilary]    

1) [Simler-Williamson & Germino 2022](https://www.nature.com/articles/s41467-022-31102-z)

## Due Mon. 3/6  

1) Angrist & Pischke **2008**, Chapter 5   

## Due Wed. 3/8 [Meghan & Tom]    

1) Dee et al., in press, and RMarkdown   
2) Byrnes & Dee, in prep and RShiny

#### Optional  
3) [Meehan et al. 2011](https://doi.org/10.1073/pnas.1100751108) vs. [Larsen 2013](https://doi.org/10.1073/pnas.1301900110)    
4) [Grace et al. 2016](https://www.nature.com/articles/nature16524) vs. Dee et al., in press  
5) [Dudney et al. 2021](https://www.nature.com/articles/s41467-021-25182-6)  

## Due Mon. 3/13  

1) Angrist & Pischke **2015**, Chapter 3 (note: this is in *Mastering ‘Metrics*)   
2) Kendall book chapter (on Canvas)    

## Due Wed. 3/15 [Max & Tyler]      

1) [Sims 2010](https://www.sciencedirect.com/science/article/pii/S0095069610000586)   
2) [MacDonald & Mordecai 2020](https://www.pnas.org/doi/10.1073/pnas.1905315116)

## Due Mon. 3/20  

1) Angrist & Pischke **2015**, Chapter 4 (note: this is in *Mastering ‘Metrics*) 

## Due Wed. 3/22 [Aly & John]    

1) [Englander 2019](https://doi.org/10.1038/s41893-019-0389-9)   
2) [Noack et al. 2022](https://doi.org/10.1111/ajae.12274)  

Optional additional paper: [Burgess et al. 2019](https://osf.io/preprints/socarxiv/67xg5/)

## Due Mon. 4/3  

No readings - come prepared with your causal question to begin your project.

In class, start your projects. We have provided a template[https://docs.google.com/presentation/d/1hyi58he1UIxFMMv7LF-HKWMphYNofOUQbtD_Ui_i3Gw/edit?usp=sharing] to provide some structure and facilitate your small group discussions.

## Due Wed. 4/5  

1:1 consultations with Laura and Katherine in lieu of class. Schedule to sign up here[https://docs.google.com/spreadsheets/d/1zCzG5zejrPa7gjMcVOseEWRs0y5cBAcJ1IXRZZyLcPM/edit?usp=sharing]

## Due Mon. 4/10

No readings - Presenting or discussing your project question and DAG for feedback

## Due Wed. 4/12  

No readings - Presenting or discussing your project question and DAG for feedback

## Due Mon. 4/17
### Tentative: Replication/Reproducibility/Pre-registration  
1) Kimmel et al., in press 

## Due Wed. 4/19

Projects

## Due Mon. 4/24

Projects

## Due Wed. 4/26
### Generalizability in experimental and observational studies  
Visit from Dr. [Rebecca Spake](https://www.reading.ac.uk/ecology/staff/rebecca-spake)

1) [Spake et al. 2022 Improving quantitative synthesis to achieve generality in ecology](https://www.nature.com/articles/s41559-022-01891-z)

Optional

1) [Korell et al. 2019](https://doi.org/10.1111/gcb.14797)  
2) [Spake et al. 2021](https://onlinelibrary.wiley.com/doi/epdf/10.1111/ele.13641)  

## Due Mon. 5/1

Project Presentations

## Due Wed. 5/3

Project Presentations

## Potential additional units
### Generalizability in experimental and observational studies  
1) [Korell et al. 2019](https://doi.org/10.1111/gcb.14797)  
2) [Spake et al. 2022](https://www.nature.com/articles/s41559-022-01891-z)  
3) [Spake et al. 2021](https://onlinelibrary.wiley.com/doi/epdf/10.1111/ele.13641)  

### Heterogeneous treatment effects  

### Replication/Reproducibility/Pre-registration  
1) Kimmel et al., in press

### Deeper dive into mechanisms and mediation analysis 
